AutotextBoot.Load([
    "autotext_SC",
    "UI_Text_SC",
    "TaskHint_Text_SC",
    "Notes_Text_SC",
    "Cellphone_Text_SC",
    "Credits_Text_SC",
    "Project_Text_SC",
    "Texting_Text_SC",
    "Tutorial_Text_SC"
])
