function Cellphone_Text_SC() {
    AutotextInit.Create({
        PHONE_Contact01: "Ned",
        PHONE_Contact02: "Dagny",
        PHONE_Contact03: "Alex",
        PHONE_BG01: "<f2><c4><hc><vc>Team Tui",
        PHONE_BG02: "<f2><c4><hc><vc>Tesla",
        PHONE_BG03: "<f2><c4><hc><vc>Thornton Hall",
        PHONE_BG04: "<f2><c4><hc><vc>Ruined House",
        PHONE_BG05: "<f2><c4><hc><vc>Loch Lomond",
        PHONE_BG06: "<f2><c4><hc><vc>Wyvern's Gate",
        PHONE_BG07: "<f2><c4><hc><vc>From Camera",
        PHONE_RingBack01: "<f2><c4><hc><vc>Classic",
        PHONE_RingBack02: "<f2><c4><hc><vc>Wildlife",
        PHONE_RingBack03: "<f2><c4><hc><vc>Vibes",
        PHONE_RingBack04: "<f2><c4><hc><vc>Action Hats",
        PHONE_RingBack05: "<f2><c4><hc><vc>Toys",
        PHONE_RingBack06: "<f2><c4><hc><vc>Wind Up",
        PHONE_RingBack07: "<f2><c4><hc><vc>Vintage Future",
        PHONE_RingTone01: "<f2><c4><hc><vc>Classic",
        PHONE_RingTone02: "<f2><c4><hc><vc>Glockenspiel",
        PHONE_RingTone03: "<f2><c4><hc><vc>News",
        PHONE_RingTone04: "<f2><c4><hc><vc>DJ",
        PHONE_RingTone05: "<f2><c4><hc><vc>Skylark",
        PHONE_RingTone06: "<f2><c4><hc><vc>Arcade",
        PHONE_RingTone07: "<f2><c4><hc><vc>Mystery",
        PHONE_AlertSound_01: "<f2><c4><hc><vc>Alert",
        PHONE_AlertSound_02: "<f2><c4><hc><vc>Drip",
        PHONE_AlertSound_03: "<f2><c4><hc><vc>Chime",
        PHONE_AlertSound_04: "<f2><c4><hc><vc>Metal",
        PHONE_AlertSound_05: "<f2><c4><hc><vc>Beeps",
        PHONE_AlertSound_06: "<f2><c4><hc><vc>Video Game",
        PHONE_AlertSound_07: "<f2><c4><hc><vc>Zip",
        PHONE_NoMessages: "<c4>You do not currently have any messages."
    });
}