function Notes_Text_SC() {
    AutotextInit.Create({
        NOTE01: "Dagny said that the key to finding the treasure is learning about the ship.",
        NOTE02: "According to Dagny, Elisabet has a key to Magnus' cabin.",
        NOTE03: "The ship alarm is in the captain's chair.",
        NOTE04: "Magnus' crystal collection needs four colors of each crystal in every row and column, with no more than two of the same color next to each other.",
        NOTE05: "The number 86 was carved into the mast.",
        NOTE06: "Scraping off the barnacles revealed the number 26.",
        NOTE07: "The pins created the number 14 on the old map.",
        NOTE08: "The letters revealed in Magnus' code were E, V, F, W, M, S, R, D, C, U, J and L.",
        NOTE09: "The numbers revealed on the soundings chart were 11, 14, 26 and 35.",
        NOTE10: "<c18>Arrange the pieces so that every row and column has one of each design.",
        NOTE11: "<c18>Find the differences between the two mirrored sides.",
        NOTE12: "<c18>Light up all the numbers by pressing the correct sections.",
        NOTE13: "<c18>Find all the words. Left click to select a letter from a row, right click to select a letter from a column.",
        NOTE14: "<c18>Drop the token in the slots to turn all of the lion heads upright.",
        NOTE15: "<c18>Arrange the overlapping pieces to recreate the full image.",
        NOTE16: "<c18>Mix elements to form volcanic winter.",
        NOTE17: "<c18>Arrange the images to show the steps needed to create each knot.",
        NOTE18: "<c18>Arrange the crystals according to Magnus' note about the crystal collection.",
        NOTE19: "<c18>Place the number pieces so that each piece is the sum of the pieces directly below it.",
        NOTE20: "<c18>Place the spark plugs and connectors in their correct locations.",
        NOTE21: "<c18>Arrange the tines to correctly play Elisabet's song.",
        NOTE22: "<c18>Match images to create a single compound word for each pair.",
        NOTE23: "<c18>Place the pins according to the notebook's code.",
        NOTE24: "<c18>Create enough white lights to fill the lighthouse, using your mouse or keyboard arrows.",
        NOTE25: "<c18>Recreate the numbers written in the corner on the big dial.",
        NOTE26: "<c18>Get all the wooden sections pressed down.",
        NOTE27: "<c18>Place the numbers so that totals shown in the overlapping sections is the sum of those circles' individual numbers.",
        NOTE28: "<c18>Match the sails to their name.",
        NOTE29: "<c18>Arrange the toys according to the row and column rules.",
        NOTE30: "<c18>Move the sliding shape to the yellow treasure mark, using your mouse or keyboard arrows.",
        NOTE31: "<c18>Divide the board into groups of six, with no group touching another.",
        NOTE32: "<c18>Find the location that reveals the correct set of sounding numbers in all four of the locator's holes.",
        NOTE33: "<c18>Fill in the three squares to complete the sequence used in each of the rows.",
        NOTE34: "<c18>Place the numbers so that one of each number is within each outlined large triangle, horizontal row and diagonal row.",
        NOTE35: "<c18>Place the pieces so that each piece covers the correct set of numbers to equal one of the five target totals."
    });
}