AutotextInit.Create({
  INV_KEY_AW: "AW Key",
  INV_BUSINESS_CARD: "Business card",
  INV_CODED_NOTE: "Strange note",
  INV_DECODED_NOTE: "Strange note",
  INV_FLYER_PIECE: "Flyer piece",
  INV_FRANCES_LETTER: "Letter",
  INV_FRONTKEY: "Hathorne House Key",
  INV_GHEQUIPMENT: "Ghost Hunting Equipment",
  INV_CROWBAR: "Crowbar",
  INV_ICOSAHEDRON: "Icosahedron",
  INV_JACKET: "Jacket",
  INV_LANTERN: "Lanter",
  INV_LIGHTER: "Lighter",
  INV_SPRAYCAN: "Rust-B-Gone",
  INV_SEWALLS_LETTER: "Sewall's Letter",
  INV_TABLEN: "Tablet",
  INV_TICKET: "Tour ticket",
  INV_TORNPLANETICKET: "Torn Plane Ticket",
  INV_USBSTICK: "USB Stick",
  INV_WATERMAP: "Waterworks Map",
  INV_WILL: "Will",
  INV_CAT_CAKE: "Cat Pancake",
  INV_FRANKENSTEIN_CAKE: "Frankenstein Pancake",
  INV_GHOST_CAKE: "Ghost Pancake",
  INV_PIRATE_CAKE: "Pirate Pancake",
  INV_PUMPKIN_CAKE: "Pumpkin Pancake",
  INV_WEREWOLF_CAKE: "Werewolf Pancake",
  INV_WITCH_CAKE: "Witch Pancake",
  SC_DROWN: "SC Drown",
  SC_FREEZE: "SC Freeze",
  SC_CRUSHED: "SC Crushed",
  SC_Caught: "SC_Caught",
  META_Captain: "Row, row, row your boat...",
  META_Cook: "Turning cute animals into entrees like a pro!",
  META_Explorer: "Intentional, or just bad at mazes?",
  META_Kitsch: "Compulsive spender or completionist? You decide!",
  META_Linguist: "\222\250 ert Fr\225b\230!",
  META_Lookout: "Not afraid of heights",
  META_Receptionist: "Lots of time on your hands, eh?",
  META_Relationship: "Put a little love in your heart!",
  META_Tide: "It only took you a month to solve the case!",
  META_Charmed: "Your phone must be pretty heavy by now.",
  META_Egged: "Time to make an omelet.",
  META_Spoiler: "Nice job on the GameFAQs usage!",
  META_TriviaTamer: "You DO Know Jack!",
  CodePuzzleHelp: "Left Click to add to a row.<n>Right Click to add to a column.",
  SlidePuzzleHelp: "Click the arrows in the lower right to move the piece. You may also use the arrows on your keyboard.",
  SequenceJR_01: "<b>Directions:",
  SequenceJR_02: "",
  SequenceJR_03: "Each row, column and diagonal contains exactly two of each dog toy.",
  SequenceJR_04: "",
  SequenceJR_05: "<b>Rows:",
  SequenceJR_06: "",
  SequenceJR_07: "1 - Both Puffins are to the right of both Dogs",
  SequenceJR_08: "2 \150 No adjacent toys of the same kind",
  SequenceJR_09: "3 \150 No Ponies in the left half of cupboard",
  SequenceJR_10: "4 \150 The first two toys in the row are a Dog and then a Pony",
  SequenceJR_11: "5 \150 The Dogs are last two toys in the row",
  SequenceJR_12: "6 \150 Pony and Puffin alternate in the last four spots",
  SequenceJR_13: "",
  SequenceJR_14: "<b>Columns:",
  SequenceJR_15: "",
  SequenceJR_16: "A \150 The Puffins are adjacent",
  SequenceJR_17: "B \150 Dogs are at the top and bottom of the column",
  SequenceJR_18: "C \150 The middle two spots are Dogs",
  SequenceJR_19: "D \150 Both Dogs are somewhere above both Ponies",
  SequenceJR_20: "E \150 Both Dogs are somewhere between the Ponies",
  SequenceJR_21: "F \150 Mirrored pattern across the center",
  SequenceSR_01: "<b>Directions:",
  SequenceSR_02: "",
  SequenceSR_03: "Each row, column and diagonal contains exactly two of each dog toy.",
  SequenceSR_04: "",
  SequenceSR_05: "<b>Rows:",
  SequenceSR_06: "",
  SequenceSR_07: "1 - Both Puffins are to the right of both Dogs",
  SequenceSR_08: "2 \150 No adjacent toys of the same kind",
  SequenceSR_09: "3 \150 No Ponies in the left half of cupboard",
  SequenceSR_10: "4 \150 Both Dogs are somewhere to the left of both Puffins",
  SequenceSR_11: "5 \150 The Puffins are between the Ponies",
  SequenceSR_12: "6 \150 The Dogs are adjacent",
  SequenceSR_13: "",
  SequenceSR_14: "<b>Columns:",
  SequenceSR_15: "",
  SequenceSR_16: "A \150 The Puffins are adjacent",
  SequenceSR_17: "B \150 Dogs on outside edges",
  SequenceSR_18: "C \150 The Dogs sit between the Puffins ",
  SequenceSR_19: "D \150 Both Dogs are somewhere above both Ponies",
  SequenceSR_20: "E \150 Both Dogs are somewhere between the Ponies",
  SequenceSR_21: "F \150 Mirrored pattern across the center",
  DIARY01: "<c3>I've arrived safe and sound in Iceland - I'm here to investigate a missing sea captain. The temperature here is about a million and a half degrees below freezing. At least, that's what it feels like.",
  DIARY02: "<c3>Dagny says that the key to finding Magnus is finding that lost treasure. I need to get on board that ship and have a look around.",
  DIARY03: "<c3>Soren seems pleasant, if a little strange. He also appears to be terrified of the other townspeople. I'm sure he'll be a useful resource if I need help, as long as he doesn't get tarred and feathered first.",
  DIARY04: "<c3>Elisabet sure has a fiery temper. I need to try and get through to her.",
  DIARY05: "<c3>I've met Gunnar, the ex-sailor. It seems like he lives at the pub, more or less. I wonder why?",
  DIARY06: "<c3>It sounds like Elisabet and Magnus used to be in a relationship. Then Magnus suddenly calls the whole thing off and goes missing right afterwards. The timing's a little too perfect.",
  DIARY07: "<c3>Soren's journal revealed that he's desperately in need of cash for some thinly-detailed academic pursuits. Then again, the whole world's in need of cash. I'm going to need more proof.",
  DIARY08: "<c3> Ned's not happy that I missed our anniversary. Oops. Maybe I can make it up to him if I bring him a souvenir? I should check out the gift shop. I wonder what he'd like?",
  DIARY09: "<c3>Dagny has gone missing. There were signs of a struggle in the snow. The prints were large -- there's only one person who could've made prints that size. I'm worried.",
  DIARY10: "<c3>Those mutoscopes in the pub make the town's history sound so adventurous... but behind every tale like that, there's a true story lying hidden.",
  DIARY11: "<c3>Dagny kindly left her password written down on a regular sticky note. Bad for her digital security practices, good for me!",
  DIARY12: "<c3>I've met a radio tower controller named Alex. She seems really helpful, if a little odd. I should give her a call if I have a question about the ship, I think.",
  DIARY13: "<c3>Apparently, Gunnar's tried to take down the festival a number of times. Kidnapping Magnus would be the obvious way to ruin a party.",
  DIARY14: "<c3>I helped out in the pub kitchen just now. I didn't ask questions about those food containers. Apparently, the Icelandic diet can be summed up as 'let's eat every cute ocean creature we come across!'",
  DIARY15: "<c3>Looks like Sonny Joon has been through this town. He and I have an odd history, but I most recently encountered him in New Zealand, where he tried to hijack a reality TV show. I seem to be constantly following in his footsteps, intentional or not. What's he up to in Iceland? What does this mean?",
  DIARY16: "<c3>Sonny has some really... interesting... ideas about me. Note to self: ask George to construct cyborg exoskeleton for future investigations.",
  DIARY17: "<c3>Ned's acting so strangely. I'm growing more worried every time he calls. What isn't he telling me? What is he hiding?",
  DIARY18: "<c3>I found Magnus's private journal. It's been a rough year for him. I suppose that explains his fervent obsession with the Heerlijkheid, and his break-up with Elisabet.",
  DIARY19: "<c3>Dagny won't tell me anything at all about herself. Maybe Ned or Alex can help shed some light on her.",
  DIARY20: "<c3>Looks like Elisabet's in a pretty dire financial situation. As someone who frequently arrives at international destinations with zero cash in hand, I totally relate.",
  DIARY21: "<c3>Elisabet's letters talk about wanting to leave Skipbrot. I wonder if she feels trapped here. I wonder if I'd feel the same, had I never left home.",
  DIARY22: "<c3>I solved that board full of little squares, and it seemed to open something else on the ship. I wonder how many parts of the ship are mechanically interconnected?",
  DIARY23: "<c3>Today is an average day, all things considered. I climbed out onto a wooden lion figurehead to twist its hair around and find a tiny mystery wheel. It's still dark out. Business as usual.",
  DIARY24: "<c3>The island can't be reached at low tide, but the tides change often. If I take a short nap at the Missti Skip, I'm sure the waterline will be different.",
  DIARY25: "<c3>Dagny tricked me; she was never in any danger at all, and just wanted to lay low and hunt on her own. Why would she lie to me like that?",
  DIARY26: "<c3>Solved Magnus's weird wall of viking crystals. Where does he get the cash to build all this? That's the real mystery here.",
  DIARY27: "<c3>The footlocker in Magnus's cabin contained Elisabet's 'anniversary gift': A music box. If this is 'rightfully hers,' does that mean it's from the original captain? Why would Magnus hide it?",
  DIARY28: "<c3>Elisabet was keeping Magnus's dog Tumi in that deck closet. Can't figure out of that makes her more or less suspicious. Tumi seems happy and well cared-for, at least.",
  DIARY29: "<c3>Soren's alibi doesn't add up. I need to keep a close eye on him. I thought I could count on him, at least, to watch my back, but... maybe not.",
  DIARY30: "<c3>I found some of Magnus's poetry: nautical-themed limericks. Sounds like he and Ned would get along swimmingly. (Heh.)",
  DIARY31: "<c3>The ice caves near town are... vast, and dangerous, and too dark even for moonshine to reach them. I should see if I can find any clues as to what might be in there.",
  DIARY32: "<c3>Dear diary: got pushed into a bilge full of freezing water today and had to solve an arcane lock to avoid drowning. Being a teenage girl is hard.",
  DIARY33: "<c3>Ned told me he loved me. We've been together a long time now. I should've expected it, but it still somehow caught me by surprise. I... think I really hurt him. I hope he'll find a way to forgive me.",
  DIARY34: "<c3>I saw what was inside Gunnar's box. I can't imagine losing my entire family. Things were rough after Mom died, but Dad always managed to stay strong somehow. I need to give him a big hug when I get home.",
  DIARY35: "<c3>Ned told me he loved me. We've been together a long time now. I should've expected it, but it still somehow caught me by surprise. I can't stop smiling, despite myself. It's freezing out, but I feel so warm.",
  DIARY36: "<c3>Looks like Lawrence was hiding a little more about his piracy-filled past than he let on. And the town's turned a blind eye to it all. I wonder where the treasure originally came from? Maybe I'll never know.",
  DIARY37: "<c3>Found a false wall in the hold, with the captain's journal inside. I think I'm the first to find it -- which means I alone have the key to finding the treasure. The kidnapper must be getting desperate.",
  DIARY38: "<c3>The treasure was never on the ship at all. And neither is Magnus. Whoever trapped me in that bilge knows I'm on to them -- I'm sorry now that I ever suspected Elisabet.",
  DIARY39: "<c3>Those marks on the wall... Soren's behind the kidnapping. His lie about his alibi, his 'funding problems,' his anger towards the town... it all finally makes sense.",
  DIARY40: "<c3>The treasure's final location is in those ice caves outside town. That must be where Magnus is, too. I've gotta get out there before it's too late.",
  Text_MK_Paranoia_01: "Something is following me. Lock everything down.",
  Text_DS_Paranoia_02: "Okay. Mr. Melodramatic. Are we starting to get just a little paranoid? Did you finish clearing the barnacles off that dock pylon next to the ladder?",
  Text_MK_Paranoia_03: "I'm serious. You'll have to wait on the final piece we discussed.",
  Text_DS_Paranoia_04: "What? Where are you putting it?",
  Text_MK_Paranoia_05: "Bed frame. On the ship. Magic circles. The key is the overlapping sections.",
  Text_MK_Paranoia_06: "Five pieces... You have one. I have one. Where are the others? Dagny, who's been watching us?",
  Text_DS_Paranoia_07: "You're just being paranoid. Calm down, have a bath, eat some fermented... whatever-you-people-eat. I'll see you in the morning."
})
