function TaskHint_Text_SC() {
    AutotextInit.Create({
        TASK01: "Explore the port.",
        TASK02: "Find a way onto the ship.",
        TASK02H1: "Ask around.",
        TASK02H2: "Check in at the culture center.",
        TASK03: "Explore the culture center.",
        TASK04: "Label the ship sails.",
        TASK04H1: "Look around for information about sailing.",
        TASK04H2: "Check inside the wheelhouse.",
        TASK04H3: "Topgallant sails are higher than topsails.",
        TASK04H4: "The jib and the spritsail are attached to the bowsprit.",
        TASK04H5: "Place the letters to read, from top to bottom, A E K B H O F N D J M C I L G.",
        TASK05: "Explore the ship's deck.",
        TASK06: "Get the item Gunnar is using as a coaster.",
        TASK06H1: "Wait for a time when he's not around, then look around his chair.",
        TASK07: "Try contacting outside help on the radio.",
        TASK07H1: "The logs mentioned Dagny having a key.",
        TASK08: "Explore the Captain's quarters.",
        TASK09: "Open the Captain's desk.",
        TASK09H1: "The rules for filling in the missing squares is seen in each row.",
        TASK09H2: "The colors and numbers are not related to each other.",
        TASK09H3: "Each row has four red and three yellow squares.",
        TASK09H4: "The numbers' totals are key.",
        TASK09H5: "The numbers in each row add up to 9.",
        TASK09H6: "Fill in the top square yellow with 1, middle square yellow with 3 and bottom square red with 1.",
        TASK10: "Find out what's inside the carved wooden box.",
        TASK10H1: "Get all the tiles pressed down. Try starting with the brighter yellow triangle in the lower left corner.",
        TASK10H2: "Press the triangle on the right edge of the middle row next.",
        TASK10H3: "Finish by pressing the middle triangle in the middle row, then the triangle at the very top.",
        TASK11: "Figure out the importance of the langspil.",
        TASK11H1: "Check out the instruments in the Missti Skip.",
        TASK11H2: "Find all of the differences in the carving.",
        TASK11H3: "Some of the differences are shown.",
        TASK11H4: "Find all of the difference shown.",
        TASK12: "Break the code in Magnus' notebook.",
        TASK12H1: "Look for long words or unique letters first. Jackstay is both of those.",
        TASK12H2: "Jackstay is located in the fourth row.",
        TASK12H3: "The first three columns contain the words luff, purser and rake.",
        TASK12H4: "The last three rows contain the words bilge, bowsprit and oakum.",
        TASK12H5: "Fill the grid as shown.",
        TASK13: "Figure out the meaning of the letters from Magnus' notebook.",
        TASK13H1: "The notebook mentioned a map, which is located in the quarters.",
        TASK13H2: "You'll need pins to mark the letters.",
        TASK13H3: "The pins are in the cupboard,",
        TASK13H4: "Place the pins on the marked letters from the notebook.",
        TASK13H5: "Place pins on C, D, E, F, J, L, M, R, S, U, V and W.",
        TASK14: "Explore the hold.",
        TASK15: "Take a snowmobile out of town.",
        TASK15H1: "You'll need a key first. Look around to see who might have one.",
        TASK15H2: "The festival flyer mentioned seeing Elisabet for snowmobile trips.",
        TASK15H3: "Elisabet runs the snowmobiles - try looking around her business for a gas can.",
        TASK16: "Explore the Missti Skip.",
        TASK17: "Check out Magnus' cabin.",
        TASK17H1: "Dagny mentioned that Elisabet has a key to the cabin in her bag.",
        TASK17H2: "Find a way to distract Elisabet.",
        TASK18: "Explore the cabin.",
        TASK19: "Arrange the dog toys.",
        TASK19H1: "You'll need to find some clues first.",
        TASK19H2: "Try working through the clues repeatedly.",
        TASK19H3: "Start with the clues for Row 4 and Column B.",
        TASK19H4: "The first toys in the top row are pony, dog, pony, dog.",
        TASK19H5: "Arrange the toys as shown.",
        TASK20: "Discover the secret of the cabin's crystals.",
        TASK20H1: "Start with areas where two adjoining crystals share the same color. The crystals on either side of the pair will be the opposite color.",
        TASK20H2: "The crystal in the lower left corner is pink.",
        TASK20H3: "The top corner is as shown.",
        TASK20H4: "Fill the board as shown.",
        TASK21: "Snoop behind the culture center's counter.",
        TASK22: "See what's on Soren's tablet.",
        TASK22H1: "Look around the culture center for the clue on which element to create.",
        TASK22H2: "Create Volcanic Winter - try starting with elements of a volcano.",
        TASK22H3: "Mix Earth and Fire to form Lava.",
        TASK22H4: "Mix the following pairs: Fire and Air, Earth and Air, Lava and Energy, Desert and Energy, Eruption and Dust Cloud.",
        TASK23: "Repair the lighthouse.",
        TASK23H1: "Find some transportation that will get you to the island.",
        TASK23H2: "Track down the lighthouse key.",
        TASK23H3: "The key is in the Captain's quarters.",
        TASK23H4: "Check in with Alex.",
        TASK23H5: "Create five white lights by combining blues to make green, greens to make red, reds to make multi-colored, and multi-colored to make white.",
        TASK24: "Escape the lighthouse.",
        TASK24H1: "The number in a box is the sum of the two boxes beneath it. Try starting in the lower right corner.",
        TASK24H2: "The lower right box is 8 and the upper left is 28.",
        TASK24H3: "The middle box of the third row is 11.",
        TASK24H4: "Enter the numbers as shown.",
        TASK25: "Fix the dinghy's motor.",
        TASK25H1: "Locate some printed materials that will help. They can both be found in the culture center.",
        TASK25H2: "Ask Soren for help and purchase the Iceland book from the gift store.",
        TASK25H3: "Arrange the spark plugs to add up to the total on a connector wire.",
        TASK25H4: "The connectors are placed, from top to bottom: sext\225n, n\237u, n\237tj\225n, \254rett\225n.",
        TASK25H5: "Place the spark plugs, from top to bottom: red (left column) t\243lf, tveir, t\237u, fimm; black (right column) fj\243rir, sj\246, n\237u, \225tta; then place the connectors as listed above.",
        TASK26: "Snoop Elisabet's bag.",
        TASK26H1: "You'll need to distract her. Locate something that will draw her attention to another part of the ship.",
        TASK26H2: "Contact Alex for help.",
        TASK26H3: "Sound the alarm on the Captain's chair in the wheelhouse.",
        TASK27: "Discover the importance of the crow's nest.",
        TASK27H1: "Make sure you're looking at the original crow's nest, not a replica.",
        TASK27H2: "Start creating groups of six in the upper left corner. There will be four groups of six touching the left edge.",
        TASK27H3: "Press down the first two pieces in the top three rows. Repeat the shape three times along the left edge.",
        TASK27H4: "Arrange the board as shown.",
        TASK28: "Snoop Dagny's luggage.",
        TASK28H1: "Search around for the missing luggage key.",
        TASK28H2: "Dagny's note mentioned seeing Tumi walk off with the key.",
        TASK29: "Search the fallen heater for clues.",
        TASK30: "Break into Dagny's phone.",
        TASK30H1: "Look around to see if she dropped anything that might help.",
        TASK30H2: "Check the hold of the ship.",
        TASK30H3: "The password is SCUTTLEBUTT.",
        TASK31: "Find out the importance of the Captain's bed frame.",
        TASK31H1: "Head to the Captain's quarters on the ship.",
        TASK31H2: "Look for sum totals that can only have one possible group of numbers, like 23.",
        TASK31H3: "Use the 6, 8 and 9 to create 23.",
        TASK31H4: "The 9 is used to create 10.",
        TASK31H5: "Place the numbers as shown.",
        TASK32: "Escape the bilge.",
        TASK32H1: "You'll need the bottom dial to show 21 on the top, 15 on the left and 21 on the right. Try creating 15.",
        TASK32H2: "There are no sixes used to create 15.",
        TASK32H3: "The first two numbers to create 15 are both four.",
        TASK32H4: "Create 15 by spinning the dials to 4, 4, 1, 1, 5.",
        TASK33: "Figure out the sounding depth numbers.",
        TASK33H1: "Track down the locator compass first. Both pieces are on the ship.",
        TASK33H2: "Look around for the two reference points mentioned by Magnus.",
        TASK33H3: "The reference points are 11 and 26. Be sure to use the correct map.",
        TASK33H4: "Using the chart from 1784, place the locator compass as shown.",
        TASK34: "Figure out what the lock in the cupboard opens.",
        TASK34H1: "You'll need to figure out what numbers to input. See if Magnus left any clues lying around.",
        TASK34H2: "Try using the numbers from the sounding depth chart.",
        TASK34H3: "Enter the numbers 11, 14, 26, 35.",
        TASK34H4: "Look below decks.",
        TASK35: "Open the panel in the hidden room.",
        TASK35H1: "See if anyone can help.",
        TASK35H2: "Fill in sections, remembering that diagonal connections count towards a number's total sections.",
        TASK35H3: "Fill in the section to the left of the 1 on the left side.",
        TASK35H4: "The 4 shares two sections with one of the 2s.",
        TASK35H5: "Fill in the panel as shown.",
        TASK36: "Rebuild the mechanical contraption in the hold.",
        TASK36H1: "You'll need to find the five missing parts. They're hidden in other areas of the ship and town.",
        TASK37: "Explore the ice caves.",
        TASK37H1: "You'll need a flashlight. Look around for one.",
        TASK37H2: "Check the ship's hold.",
        TASK37H3: "Buy some batteries from the gift shop.",
        TASK38: "Figure out the importance of Tumi's chew toy.",
        TASK38H1: "Follow the clues Magnus wrote down in his notes to Dagny.",
        TASK38H2: "His notes mentioned Tumi's carrier on the ship.",
        TASK38H3: "Keep an eye out for dog toys.",
        TASK39: "Retrieve and return Gunnar's box.",
        TASK39H1: "He mentioned it was inside the Missti Skip.",
        TASK39H2: "Look behind the shield.",
        TASK40: "Figure out what the sketches create.",
        TASK40H1: "Find something to build the sketches off of. Try looking around Magnus' things.",
        TASK40H2: "You'll need to find all of the sketches first. One set can be found on the ship's deck.",
        TASK40H3: "The others are out in the ice caves, in the captain's quarters or already found by Dagny and Gunnar.",
        TASK40H4: "Start with building off the center, looking for easily distinguished overlap areas.",
        TASK40H5: "Arrange the sketches as shown.",
        TASK41: "Follow up on the image created by the sketches.",
        TASK41H1: "Find the location where the item is located.",
        TASK41H2: "Look in the lighthouse.",
        TASK41H3: "Start by placing the 7, 8 and 9 in the middle triangle on the left to complete it.",
        TASK41H4: "Place all remaining 7s next, starting with a 7 in the single opening across the bottom.",
        TASK41H5: "Place all 9s next. A 4 goes in the middle row of the triangle with the fixed 8 and 9.",
        TASK41H6: "Arrange the pieces as shown.",
        TASK42: "Find Dagny.",
        TASK42H1: "Keep an eye out for her throughout all areas.",
        TASK43: "Figure out what the token from Dagny is for.",
        TASK43H1: "Look around for an object that has a similar design element.",
        TASK43H2: "Take a close look at the ship's figurehead.",
        TASK43H3: "The token turns heads as it passes through tracks. The direction of the head affects which path the token takes.",
        TASK43H4: "Start by dropping the token in the left slot, then the center slot.",
        TASK43H5: "Continue from the previous step and drop the token in the center, right, center, center, center.",
        TASK44: "Open the right side of the Captain's box.",
        TASK44H1: "Pieces can stack on top of each other to change the shape.",
        TASK44H2: "The top row is circle outline, filled diamond, filled square, square outline, diamond outline, filled circle.",
        TASK44H3: "Arrange the shapes as shown.",
        TASK45: "Open the left side of the Captain's box.",
        TASK45H1: "Track down the missing piece first.",
        TASK45H2: "Start by changing the red fish to a red star, then a blue star.",
        TASK45H3: "You'll need to change to a green fish before a green jellyfish.",
        TASK45H4: "Navigate through as shown.",
        TASK46: "Discover the importance of the music box.",
        TASK46H1: "Uncover how music ties back to the original Captain.",
        TASK46H2: "There's a book that will help at the Missti Skip.",
        TASK46H3: "The first note from the sheet music is a low g - count the markings on the tines to find the one for low g, then place that comb where the low g will strike the first bump to play.",
        TASK46H4: "The second note is not directly next to the low g on the cylinder or the combs.",
        TASK46H5: "Place the tines as shown.",
        TASK47: "Track down the treasure's hidden room from the Captain's manuscript.",
        TASK47H1: "You'll need to locate all of the pieces of the manuscript first.",
        TASK47H2: "The final room is hidden behind an ice wall.",
        TASK47H3: "Look around for identifying features in the tunnels that match those mentioned by Lawrence.",
        TASK47H4: "From the entrance keep going forward until the yellow marker, climb up and go down past the yellow and pink markers, continue straight at the blue and red markers, continue pass the pink, then yellow markers and go up when the tunnel splits. Turn right at the blue marker, enter the large cavern and head into the tunnel between the blue and pink markers. Continue until the dead end, then break through the ice wall.",
        TASK48: "Find a treasure for Soren.",
        TASK48H1: "The Captain's manuscript holds the key.",
        TASK48H2: "The decoy treasure is located in the left side of the cave when facing away from Soren.",
        TASK48H3: "Chip the ice away from the left side of the dead end opposite of Soren.",
        TASK49: "Find the real treasure.",
        TASK49H1: "The Captain's manuscript holds the key.",
        TASK49H2: "Compare the images from Lawrence's journal with the shanty lyrics.",
        TASK49H3: "Press the wind curl first, then the ship's bow.",
        TASK49H4: "Continue with the grave, ice berg, bone, compass pointing north, heart, wave, broken heart, tattered sail, sky and the stone wall.",
        TASK50: "Fix the heater.",
        TASK50H1: "One of the pieces has an edge in the lower right corner.",
        TASK50H2: "The orange piece's total is -2.",
        TASK50H3: "The purple piece touches the bottom of the grid.",
        TASK50H4: "Arrange the pieces as shown.",
        TASK51: "Discover the secret of the ship's wheel.",
        TASK51H1: "You'll need to find the ten missing tokens first. One is located in town, the others are in a building outside of town.",
        TASK51H2: "Search the Missti Skip.",
        TASK51H3: "Magnus had already found the remaining nine tokens, but didn't keep them on the ship.",
        TASK51H4: "The tokens can be found inside the stove, above the door, and on the tray table, the answering machine, the bed and the end table.",
        TASK51H5: "Arrange the tokens on the wheel to form compound words with the images. Start with pairing the rain cloud and bow to form 'rainbow.'",
        TASK51H6: "The waves represent 'sea.'",
        TASK51H7: "Create the words gunwale (whale), fireball, footstool, seahorse, starfish, riverbed, rainbow, forecastle (four), sunflower, springboard.",
        TASK52: "Find out what's inside the footlocker in the cabin.",
        TASK52H1: "Look around for clues on how to open it - this may take awhile.",
        TASK52H2: "The crystal display will open the footlocker.",
        TASK53: "Set up the knots display.",
        TASK53H1: "Start with the final step and work backwards for each knot.",
        TASK53H2: "The top knot is made as shown.",
        TASK53H3: "The knots are made as shown.",
        SRTASK01: "Search the ship.",
        SRTASK02: "Get the radio working.",
        SRTASK03: "Repair the lighthouse light for Alex.",
        SRTASK04: "Snoop Elisabet's bag.",
        SRTASK05: "Explore the town.",
        SRTASK06: "Find and return the helm's missing decorations.",
        SRTASK07: "Search the Captain's quarters for clues.",
        SRTASK08: "Find Dagny.",
        SRTASK09: "Check out Magnus' cabin outside of town.",
        SRTASK10: "Snoop behind the counter.",
        SRTASK11: "Find out what the panel in the hold is hiding.",
        SRTASK12: "Figure out what the lock in the cupboard opens.",
        SRTASK13: "Retrieve Gunnar's box.",
        SRTASK14: "Look into the ice caves from Magnus' photos.",
        SRTASK15: "Open the chest in the hold.",
        SRTASK16: "Follow up on the image created by the sketches.",
        SRTASK17: "Track down the treasure's hidden room from the Captain's manuscript.",
        SRTASK18: "Find a treasure for Soren.",
        SRTASK19: "Find the real treasure.",
        SRTASK20: "Find a light to use in the ice caves.",
        SRTASK21: "Explore the caves.",
        SRTASK22: "Figure out the importance of the contents of the footlocker.",
        SRTASK23: "Figure out the sounding depth numbers.",
        SRTASK24: "Explore the Missti Skip.",
        SRTASK25: ""
    });
}