function Tutorial_Text_SC() {
    AutotextInit.Create({
        TUT_INV_BOXCUTTER: "Box Cutter",
        TUT_STEP1: "Arrows indicate directions you can move in. Step up to the desk.",
        TUT_STEP2: "A 'hand' cursor indicates an item can be picked up or manipulated. Try taking a closer look at the letter.",
        TUT_STEP3: "You can back out of a scene when the 'back' or 'turn around' arrow appears near the bottom of the screen. When you're done reading the letter, back out to place the letter back down.",
        TUT_STEP4: "Tasks that will help you solve the case appear in your Task List as you discover clues. If there are multiple tasks available, you can open the Task List to view the full list.",
        TUT_STEP4B: "If there are multiple tasks available, you can open the Task List to view the full list.",
        TUT_STEP4C: "If you're playing as an Amateur Sleuth, your Task List will include hints for various tasks. To show a task's hints, click on the blue '?' next to the task. Try revealing a hint now.",
        TUT_STEP4D: "Let's try to find Ned's package. Step back into the room.",
        TUT_STEP5: "Some areas allow you to spin around for a full view. These areas use the 'spin around' cursor. Try spinning to the left now.",
        TUT_STEP6: "During your case, you'll be able to talk with characters. The talk cursor indicates when a character is available. Try talking with the teddy bear now.",
        TUT_STEP7: "Choose an option to respond to Mr. Woogle Woggle.",
        TUT_STEP8: "Time to find the package. Continue spinning around to the left.",
        TUT_STEP8b: "You've found the package. The look cursor indicates an object you can view up close.",
        TUT_STEP9: "Try opening the package.",
        TUT_STEP9c: "The use an inventory item cursor appears on objects that require an inventory item. Find something that will help cut open the box.",
        TUT_STEP10: "The box cutter now shows in your inventory tray. If you have multiple objects in the tray, you can slide the bar to see all items.",
        TUT_STEP11: "The box cutter now shows in your inventory tray. If you have multiple objects in the tray, you can slide the bar to see all items. Pick up the box cutter from the inventory tray and use it on the package.",
        TUT_STEP12: "Open your phone.",
        TUT_STEP12a: "Click on the camera icon and take a photo. You can view pictures later in the gallery.",
        TUT_STEP12b: "Give Ned a call. Return to the phone's main menu by pressing the 'K' home icon.",
        TUT_STEP13: "Click on your phone, choose Ned from your contacts list and make a call.",
        TUT_STEP14: "When you've finished a task, you can check it off in your Task List. Go ahead and mark your task completed.",
        TUT_STEP15: "Congratulations! <n><n>You've completed the tutorial. A quick help sheet is available in-game at all times by opening the menu, then choosing Help. You can also replay the tutorial from the Main Menu.",
        TUT_TASK: "Open the package and call Ned.",
        TUT_TASKH1: "Look around the room for Ned's package.",
        TUT_VO1_SFX: "Hi! I'm Nancy Drew, and this is my room. You're going to learn a little about how to explore my world. To begin, let's step up to my desk.",
        TUT_VO2_SFX: "Aw it's packed up tight. I'll need something sharp to open it.",
        TUT_VO3_SFX: "Aw, Ned! What a nice gift. I should give him a call.",
        TUT_VO4_SFX: "When I come across a written item on a case, it's important for me to read the entire thing. A good sleuth is thorough.",
        TUT_VO5_SFX: "Pictures come in handy as a quick reference when I move to different areas. Sometimes a single photo can save a lot of leg work!",
        TUT_VO6_SFX: "Nice work! You'll be a Master Sleuth in no time. Let's get started on a new adventure!",
        TUT_VO7_SFX: "Oh, looks like someone sent me a letter!",
        TUT_VO8_SFX: "I should take a picture to send to Ned.",
        TUT_TOPIC101_N_SFX: "<c0>Okay, Mr. Woogle-Woggle. Six cupcakes went missing from the pantry last night, and I know they didn't march out of there on their own. What do you have to say for yourself?",
        TUT_TOPIC102_SFX: "<c1>I... I have nothing to hide! I'm innocent!",
        TUT_TOPIC103A_N_SFX: "<c0>A likely story. You're lying!",
        TUT_TOPIC103B_N_SFX: "<c0>That's good. I'm trying to clear your name.",
        TUT_TOPIC104_SFX: "<c1>Look into my eyes. Is this the face of a liar?",
        TUT_TOPIC105_N_SFX: "<c0>We'll see about that.",
        TUT_TOPIC106_SFX: "<c1>I-I'll tell you anything you want to know!",
        TUT_TOPIC201_N_SFX: "<c0>My other stuffed animals tell me you've got a 'troubled past.'",
        TUT_TOPIC201B_N_SFX: "<c0>Where were you last night?",
        TUT_TOPIC201C_N_SFX: "<c0>If you didn't take those cupcakes, who did?",
        TUT_TOPIC202_SFX: "<c1>It's true I used to steal cupcakes for a quick buck. But those dark times are behind me now! I'm a good bear!",
        TUT_TOPIC203_SFX: "<c1>I was sitting right here, just like I always am! I can't move!",
        TUT_TOPIC204_SFX: "<c1>Look, Nancy. You and I both know Millie the Giraffe has had it out for me for years. Can't you see she's framing me?",
        TUT_TOPIC301_N_SFX: "<c0>Hmm. Interesting.",
        TUT_TOPIC302_N_SFX: "<c0>I'll circle back to you later, Mr. Woogle-Woggle. But don't think you're out of the woods just yet.",
        TUT_TOPIC303_SFX: "<c1>Okay. Bye Nancy.",
        TUT_NN_TUTORIAL01_N_SFX: "<c0>Hi, Ned. I got your care package!",
        TUT_NN_TUTORIAL02_SFX: "<c1>Cool! So it finally showed up?",
        TUT_NN_TUTORIAL03_N_SFX: "<c0>Yes! And you got all my favorites, too.",
        TUT_NN_TUTORIAL04_SFX: "<c1>I figured you'd like that. So\133 what's the case du jour?",
        TUT_NN_TUTORIAL05_N_SFX: "<c0>I'm at home right now -- not on a case.",
        TUT_NN_TUTORIAL06_SFX: "<c1>Wow. No puzzles to solve? No race against time? Just\133 hanging out?",
        TUT_NN_TUTORIAL07_N_SFX: "<c0>Just\133 hanging out.",
        TUT_NN_TUTORIAL08_SFX: "<c1>Well. That's pretty unusual for Ms. Super-sleuth.",
        TUT_NN_TUTORIAL09_SFX: "<c1>Enjoy your afternoon, then. I'll see you this weekend. Give my love to Hannah and your dad.",
        TUT_NN_TUTORIAL10_N_SFX: "<c0>Bye!",
        TUT_NN_TUTORIAL11_SFX: "<c1>Bye.",
        TUT_PHONENED: "Ned"
    })
}