AutotextInit.Create({
    NIL: "",
    UISAV01: "Save",
    UISAV02: "Do you want to save first?",
    UISAV03: "Yes",
    UISAV04: "No",
    UISAV05: "Do you want to overwrite the saved game?",
    UISAV06: "Do you want to quit? All unsaved progress will be lost.",
    UIOPT01: "Voice Volume",
    UIOPT02: "Effects Volume",
    UIOPT03: "Music Volume",
    UIOPT04: "Matte Color",
    UIOPT05: "Closed-Captioning",
    UIOPT08: "Fullscreen",
    UIOPT09: "Play the game in a larger window",
    UIOPT10: "Windowed",
    UIOPT11: "Play the game in a smaller window",
    UIOPT12: "Small Text",
    UIOPT13: "Large Text",
    UILOD01: "Load",
    UILOD02: "New",
    UICHT01: "<vc><hc><f15><c3>OK",
    UICHT02: "<vc><hc><f15><c3>Cancel",
    UICHT03: "<vc><hc><f15><c3>Save",
    UICHT04: "<vc><hc><f15><c3>Load",
    UICHT05: "<vc><hl><f13><c3>Game time: ",
    UICHT12: "<vc><hl><f15><c4>Search",
    UICHT13: "<vc><hl><f13><c3>Allow true:",
    UICHT14: "<vc><hl><f13><c3>Allow false:",
    UICHT15: "<vc><hl><f13><c3>Allow flags:",
    UICHT16: "<vc><hl><f13><c3>Allow brains:",
    UICHT20: "<vc><hc><f15><c3>Streams",
    UICHT21: "<vc><hc><f15><c3>Logic",
    UICHT22: "<vc><hc><f15><c3>Vars",
    UICHT23: "<vc><hc><f15><c3>Strs",
    UICHT24: "<vc><hc><f15><c3>Inventory",
    UICHT27: "<vc><hc><f15><c3>Photos",
    UICHT28: "<vc><hc><f15><c3>Cell",
    UICHT29: "<vc><hc><f15><c3>Medley",
    UICHT30: "<vc><hc><f15><c3>Area",
    UICHT31: "<vc><hc><f15><c3>Timers",
    UICHT32: "<vc><hc><f15><c3>Achievements",
    UICHT33: "<vc><hc><f15><c3>Clear all",
    UICHT34: "<vc><hc><f15><c3>Inspector",
    UICHT35: "<vc><hc><f15><c3>Copy",
    UICHT36: "<vc><hc><f15><c3>Copy All",
    TTIP01: "View your inventory",
    TTIP02: "Close your inventory",
    TTIP03: "Read your journal",
    TTIP04: "Close your journal",
    TTIP05: "Check your tasklist",
    TTIP06: "Close your tasklist",
    TTIP07: "Use your cell phone",
    TTIP08: "Close your cell phone",
    TTIP09: "Quit the game",
    TTIP10: "Save your game",
    TTIP11: "Load a game",
    TTIP12: "Change game settings",
    TTIP13: "Read the sailing manual",
    TTIP14: "Use your GPS device",
    TTIP15: "Close your GPS device",
    TTIP16: "Complete game to unlock",
    NanPhone: "PB:Nancy",
    BessPhone: "PB:Bess",
    UI_Quit01: "Click to Start a New Game",
    FGTEXT1: "Click to replay Tutorial.",
    NextHint: "<vc><hc>I need a hint",
    NextHintSpoiler: "<vc><hc>I need a solution",
    RearrangeHelp: "Right Click And Hold To Rotate.",
    LockpickHelp: "Right Click on inserted pick to remove it.",
    HELPTEXT1: "Right Click to Rotate.",
    HELPTEXT2: "Right Click to add to column",
    LINK_Website: "http://www.herinteractive.com",
    LINK_Newsletter: "http://www.herinteractive.com/newsletter-archive.php",
    LINK_Facebook: "http://www.facebook.com/NancyDrewPCGames",
    LINK_Twitter: "http://www.twitter.com/herinteractive",
    LINK_YouTube: "http://www.youtube.com/herinteractivegames",
    LINK_Pinterest: "http://pinterest.com/nancydrewgames/"
})